### ISSUE TITLE
Add Bootstrap via pipe to build process

### ISSUE THREAD

**Issue by davidsneighbour** [gethugothemes/gethugothemes-documentation-site#12]
Currently, Bootstrap is added via full compiled files in static, which makes it hard to add or configure features. It also might be overload (I don't know if the files are the full versions or cut down versions with features removed that we don't use here). See #10 

I propose to add building the stylesheets via SCSS pipe and removing unused parts. This way we can add/remove features easier. I'll add a PR in a bit.

**Comment by somratpro** [comment]
Make a PR then
