### ISSUE TITLE
Add notice about the docsite-discussion forum to all MIT licensed themes

### ISSUE THREAD

**Issue by davidsneighbour** [gethugothemes/gethugothemes-documentation-site#14]
I think it makes sense to "siphon" people that use the free themes over to the discussions area for support. Maybe even the paid users. We could add a section to the start page of each theme documentation saying something along the lines "We welcome you to add your feature requests or questions over at our discussion forum" and then "keep the free support in our community".

Maybe by adding a shortcode that shows a nice github octocat (gimmick: change the octocat based on season or time of the day) with the text in a box.

What do you think? @gethugothemes/hugo

**Comment by somratpro** [comment]
Yeah, I think it's a good idea.
