### ISSUE TITLE
Search: how to configure what is in the index?

### ISSUE THREAD

**Issue by davidsneighbour** [gethugothemes/gethugothemes-documentation-site#16]
I don't understand how the search is created or how the search index is built. From what I can check it is not "good enough" for a documentation site. I can't find `i18n` or `baseURL` for instance. It's a documentation site, so we have to provide a fulltext search for EVERYTHING that is written in content. 

Maybe via Algolia? I don't know how this scales, their free tier has 10k search requests per month included and 100k indexing "actions" which means we can add 100k pages per month to the index. In the beginning this might be enough. 

We need a "professional" search index solution that covers typos in search requests, synonyms and so on. If people can't find our content they leave. 

Step 1: How is the current search built and how can we improve on what can be found by this search?
Step 2: Let's find a flexible solution for an indexable search. I could provide a quick setup for Algolia and we could test their free tier, but I have no information about the number of search requests that are done.

**Comment by somratpro** [comment]
Hey, actually we had that before. then when we search for `i18n` it will show all the content about `i18n` in this doc from many themes. so we make it simple. Suppose you purchased Kross theme, why you will read the other theme docs? you will search Kross and get into it. now you have all the content/docs only from the Kross theme.

**Comment by davidsneighbour** [comment]
That makes sense. But one day we will have lot's of howto's that need to be indexed. Maybe by adding a frontmatter parameter that adds/hides the content of that post from the index.

**Comment by developer-evan** [comment]
Then we will also index it on documentation, don't worries
