### ISSUE TITLE
[Airspace Hugo] rewrite i18n documentation

### ISSUE THREAD

**Issue by davidsneighbour** [gethugothemes/gethugothemes-documentation-site#8]
The i18n documentation requires a complete rewrite with samples and proper information.

https://github.com/gethugothemes/gethugothemes-docs/edit/master/content/airspace-hugo/i18n-translation.md

**Comment by davidsneighbour** [comment]
Agico Hugo too: https://github.com/gethugothemes/gethugothemes-docs/edit/master/content/agico-hugo/i18n-translations.md

**Comment by developer-evan** [comment]
Hello @davidsneighbour ,

You can edit it, and make a PR if you would like to. thank  you

**Comment by davidsneighbour** [comment]
Done, can be reused via `{{< contentblock "i18n" >}}`
